# Generated by Django 5.2.14 on 2026-05-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
