# Generated by Django 5.2.14 on 2026-05-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume_file',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
