# Generated by Django 5.2.14 on 2026-05-27 17:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_application_resume_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to='candidates.candidate')),
            ],
            options={
                'unique_together': {('candidate', 'login_date')},
            },
        ),
    ]
