# Generated by Django 5.2.14 on 2026-05-23 17:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(default='Full-time', max_length=50)),
                ('priority', models.CharField(default='Normal', max_length=50)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('description', models.TextField()),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('application_form_schema', models.JSONField(blank=True, default=dict)),
                ('pipeline_stages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
