"""
Django settings for hiresync_backend project.

Generated by 'django-admin startproject' using Django 5.2.14.
"""

import os
import sys
from pathlib import Path
from urllib.parse import urlparse
from dotenv import load_dotenv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Add apps to Python path
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fallback-key')
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 't')

ALLOWED_HOSTS = [host.strip() for host in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if host.strip()]

# Application definition
INSTALLED_APPS = [
    # Daphne must be at the top of INSTALLED_APPS for Channels integration
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',
    
    # Local apps
    'authentication',
    'companies',
    'jobs',
    'candidates',
    'assessments',
    'interviews',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Put CORS first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'companies.middleware.TenantMiddleware', # Custom multi-tenant workspace context resolver
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hiresync_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hiresync_backend.wsgi.application'
ASGI_APPLICATION = 'hiresync_backend.asgi.application'

# Database Connection
import socket
db_url = os.environ.get('DATABASE_URL', '')
if db_url.startswith('postgres://') or db_url.startswith('postgresql://'):
    # Support connection poolers and SSL if needed (recommended for Supabase)
    url = urlparse(db_url)
    
    # Try resolving host and opening a fast connection check to prevent crashes on unstable/restricted networks
    use_postgres = True
    try:
        # Check DNS resolution & reachability to port 5432 (timeout of 2.0 seconds)
        s = socket.create_connection((url.hostname, url.port or 5432), timeout=2.0)
        s.close()
    except Exception as e:
        use_postgres = False
        print("\n" + "="*80)
        print(" ⚠️  DATABASE REACHABILITY ERROR: Failed to connect to remote Supabase database!")
        print(f"    Host: {url.hostname}:{url.port or 5432}")
        print(f"    Error: {e}")
        print("\n 👉 POSSIBLE CAUSES:")
        print("    1. You are offline or have a weak/unstable internet connection.")
        print("    2. A firewall, VPN, or network proxy is blocking port 5432 or DNS resolution.")
        print("\n ⚠️  FALLING BACK TO LOCAL SQLITE DATABASE (db.sqlite3) FOR OFFLINE DEVELOPMENT.")
        print("="*80 + "\n")
        
    if use_postgres:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': url.path[1:],
                'USER': url.username,
                'PASSWORD': url.password,
                'HOST': url.hostname,
                'PORT': url.port or 5432,
                'OPTIONS': {
                    'sslmode': 'prefer',
                }
            }
        }
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    # SQLite fallback with a highly visible terminal warning and setup guide
    print("\n" + "="*80)
    print(" ⚠️  WARNING: DATABASE_URL not set or not pointing to a Postgres database!")
    print(" ⚠️  Falling back to local SQLite database (db.sqlite3).")
    print(" ⚠️  Data will NOT sync with Supabase. Recruiter auth changes will be local-only.")
    print("\n 👉 TO SYNC WITH PRODUCTION SUPABASE:")
    print("    1. Copy 'backend/.env.example' to 'backend/.env'")
    print("    2. Add the following values to your '.env' file:")
    print("       DATABASE_URL=postgresql://postgres:Yash9897422911@db.kntarabupposhjhlqwob.supabase.co:5432/postgres")
    print("       SUPABASE_URL=https://kntarabupposhjhlqwob.supabase.co")
    print("       SUPABASE_JWT_SECRET=kcwYMVIO/tp2KTwydJqHc7XnsnvIoYBGVe3LGvl7BAEVIZi25FmsFo70uaRRjmxwBIRYJl5qGX1nJYSJwD5Thw==")
    print("="*80 + "\n")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# DRF configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'authentication.authentication.SupabaseJWTAuthentication',  # Custom Supabase authentication
        'authentication.authentication.RecruiterJWTAuthentication', # Custom Recruiter SimpleJWT authentication
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# Simple JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8), # 8-hour expiry for Recruiters
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
}

# Supabase Auth Settings
SUPABASE_URL = os.environ.get('SUPABASE_URL', '')
SUPABASE_JWT_SECRET = os.environ.get('SUPABASE_JWT_SECRET', '')

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True  # For dev purposes
CORS_ALLOW_CREDENTIALS = True

# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# WebSockets Channel Layers
# Use in-memory layer as dev fallback if redis config is not complete
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Media files (for resume uploads, profile photos)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Setup logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
