# Generated by Django 5.2.14 on 2026-05-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyadminprofile',
            name='photo_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='passing_ats_score',
            field=models.IntegerField(default=70),
        ),
    ]
